name: shared
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.5.0 <3.0.0"

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  hive_generator: ^0.7.1
  build_runner: ^1.10.0
  test: ^1.15.3

dependencies:
  hive: ^1.4.2
